Add `CompositeEffectBuilder` to API
JamesVeug/AgainstTheStormAPI pull request #4
Opened 2024-12-18 01:09 UTC by Forwindzz

Hi,
Here is the code for
- `CompositeEffectBuilder` API
- Example cornerstone for `CompositeEffectBuilder`
- A tiny chinese translation fix in `ExampleMod`
 
This code may have some design problems:

(1) Function Name Problem:
In `CompositeEffectModel`, they have two fields:
`hasNestedPreview` -> preview like explode range
`hasNestedStatePreview` -> preview texts 
So I design API function names in this way:
`hasNestedPreview` -> preview like explode range -> API function name: `SetNestedPreviewActionIndex(int index)`
`hasNestedStatePreview` -> preview texts ->  API function name:`SetNestedPreviewIndex(int index)`
Otherwise, it is easy to confused with `HookedEffectModel.SetPreviewDescription()`
I wonder if the name `PreviewAction` is okay.

(2) Conflict Class Names:
`Eremite.Model.Effects.Hooked.TextArgType` (from `HookedEffectModel`)
`Eremite.Model.Effects.TextArgType` (from `CompositeEffectModel`)
They have the same class name...
So in the example mod, I use alias names.
```C#
using HookedTextArgType = Eremite.Model.Effects.Hooked.TextArgType;
using CompositeTextArgType = Eremite.Model.Effects.TextArgType; // note: these two TextArgType are different!
```
Is there any better design?

2024-12-18 05:23 UTC, JamesVeug requested changes
Just requires an icon!

Note there that the API should be adding non-EffectModel support so people don't need to wait for the game to load to reference vanilla effects

2024-12-18 05:23 UTC, JamesVeug commented on ATS_API/Scripts/Effects/EffectBuilders/CompositeEffectBuilder/CompositeEffectBuilder.cs
> +        m_effectModel.rewards.ForceAdd(effect);
The API works off the assumption core EffectModels do not exist yet so mods can be written in the Awake method of their plugin.
Just realized HookedEffectBuilder also does this which isn't ideal...

Something to look into later is changing this method and others from changing m_effectModel directly but instead doing it in NewEffectData.PostSync and use EffectTypes as parameters instead.

2024-12-18 05:23 UTC, JamesVeug commented on ExampleMod/Plugin.Cornerstones.cs
> +using CompositeTextArgType = Eremite.Model.Effects.TextArgType; // note: these two TextArgType are different!
Yeah this is awkward but no dunno what else we can do either!

2024-12-18 05:23 UTC, JamesVeug commented on ExampleMod/Plugin.Cornerstones.cs
> +        AggregateProductivityBuilder = new CompositeEffectBuilder(PluginInfo.PLUGIN_GUID, "AggregateProductivity", "ModdingTools.png"); //Need to change the image
Need new icon <3

2024-12-23 22:31 UTC, Forwindzz commented
I have added an icon

2024-12-24 05:21 UTC, JamesVeug approved these changes

2024-12-24 05:21 UTC, merged